# Generated by Django 4.2.7 on 2023-12-03 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RENT", "For Rent"),
                            ("BUY", "For Sale"),
                            ("BOTH", "For Rent and Sale"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("شقة", "Apartment"),
                            ("بيت", "House"),
                            ("فندق", "Hotel"),
                            ("أماكن بديلة", "Alternative Places"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "owner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
